export type Activity = {
  id: string
  title: string
  slug: string
  category: string
  shortDescription: string
  description: string
  date: string
  time: string
  endTime: string
  location: string
  address: string
  organizer: string
  participants: number
  maxParticipants: number
  target: string
  impact: string
  achievement: string
  status: string
  registration: string
  coordinator: string
  contact: string
  partner: string
  volunteers: number
  budget: string
  fundingSource: string
  facilities: string[]
  requirements: string[]
  tags: string[]
  coverImage: string
  images: string[]
}

function img(photoId: string, w: number, h: number, crop: string): string {
  return `https://images.unsplash.com/photo-${photoId}?auto=format&fit=crop&w=${w}&h=${h}&q=80&crop=${crop}`
}

const PHOTO_LINGKUNGAN = "1758599669317-efd787d954ef"
const PHOTO_SOSIAL = "1593113646773-028c64a8f1b8"
const PHOTO_EDUKASI = "1540151812223-c30b3fab58e6"
const PHOTO_KEMANUSIAAN = "1651372381086-9861c9c81db5"
const PHOTO_KOMUNITAS = "1515187029135-18ee286d815b"

function galleryFor(photoId: string): string[] {
  return [
    img(photoId, 1200, 800, "entropy"),
    img(photoId, 1000, 750, "faces"),
    img(photoId, 900, 600, "top"),
    img(photoId, 1100, 700, "bottom"),
    img(photoId, 950, 650, "left"),
    img(photoId, 1050, 700, "right"),
  ]
}

const IMAGES_LINGKUNGAN = galleryFor(PHOTO_LINGKUNGAN)
const IMAGES_SOSIAL = galleryFor(PHOTO_SOSIAL)
const IMAGES_EDUKASI = galleryFor(PHOTO_EDUKASI)
const IMAGES_KEMANUSIAAN = galleryFor(PHOTO_KEMANUSIAAN)
const IMAGES_KOMUNITAS = galleryFor(PHOTO_KOMUNITAS)

const COVER_LINGKUNGAN = img(PHOTO_LINGKUNGAN, 1200, 800, "entropy")
const COVER_SOSIAL = img(PHOTO_SOSIAL, 1200, 800, "entropy")
const COVER_EDUKASI = img(PHOTO_EDUKASI, 1200, 800, "entropy")
const COVER_KEMANUSIAAN = img(PHOTO_KEMANUSIAAN, 1200, 800, "entropy")
const COVER_KOMUNITAS = img(PHOTO_KOMUNITAS, 1200, 800, "entropy")

export const activities: Activity[] = [
  // ===================== LINGKUNGAN (6) =====================
  {
    id: "activity-001",
    title: "Aksi Bersih Sungai Ciliwung",
    slug: "aksi-bersih-sungai-ciliwung",
    category: "Lingkungan",
    shortDescription:
      "Membersihkan aliran Sungai Ciliwung dari sampah plastik bersama warga dan relawan.",
    description:
      "Kegiatan ini mengajak warga bantaran Sungai Ciliwung, relawan Komunitas Karsa, dan siswa sekolah setempat untuk membersihkan sampah yang menumpuk di aliran sungai. Aksi ini dilatarbelakangi tingginya pencemaran plastik yang menyebabkan pendangkalan dan banjir di musim hujan. Peserta dibagi menjadi beberapa kelompok untuk menyisir titik-titik rawan sampah menggunakan perahu karet dan alat pungut sampah, lalu hasilnya dipilah untuk didaur ulang oleh bank sampah setempat.",
    date: "12 Oktober 2026",
    time: "07.00 WIB",
    endTime: "11.00 WIB",
    location: "Bantaran Sungai Ciliwung, Kelurahan Bantarjati",
    address: "Jl. Bantarjati Raya, Kelurahan Bantarjati, Bogor Utara, Bogor",
    organizer: "Komunitas Karsa bersama Karang Taruna Bantarjati",
    participants: 85,
    maxParticipants: 100,
    target: "Mengangkat minimal 500 kg sampah plastik dari sepanjang 2 km aliran sungai",
    impact:
      "Berhasil mengumpulkan 620 kg sampah, melibatkan 85 relawan, dan memicu pembentukan kelompok peduli sungai di 3 RW",
    achievement: "Melampaui target pengangkutan sampah hingga 124% dari target awal",
    status: "Akan Datang",
    registration: "Pendaftaran dibuka",
    coordinator: "Rangga Saputra",
    contact: "0812-3456-7801",
    partner: "Karang Taruna Bantarjati",
    volunteers: 24,
    budget: "Rp8.500.000",
    fundingSource: "Donasi warga dan sponsor lokal",
    facilities: ["Peralatan kebersihan", "Air minum", "Sarung tangan"],
    requirements: ["Membawa tumbler", "Menggunakan pakaian dan alas kaki tertutup"],
    tags: ["Lingkungan", "Sungai", "Relawan"],
    coverImage: COVER_LINGKUNGAN,
    images: IMAGES_LINGKUNGAN,
  },
  {
    id: "activity-002",
    title: "Gerakan 100 Pohon untuk Sukamaju",
    slug: "gerakan-100-pohon-untuk-sukamaju",
    category: "Lingkungan",
    shortDescription:
      "Menanam 100 pohon produktif di lahan kritis Desa Sukamaju untuk mencegah longsor.",
    description:
      "Lahan kritis di lereng Desa Sukamaju rawan longsor saat musim hujan, sehingga Komunitas Karsa bersama pemerintah desa menginisiasi penanaman bibit pohon durian, alpukat, dan trembesi. Warga, kelompok tani, dan pelajar SMA setempat dilibatkan langsung dalam proses penggalian lubang tanam hingga penyiraman. Selain menahan erosi, pohon produktif ini diharapkan menjadi sumber penghasilan tambahan bagi warga dalam beberapa tahun ke depan.",
    date: "5 November 2026",
    time: "06.30 WIB",
    endTime: "10.00 WIB",
    location: "Lereng Bukit Sukamaju, Kecamatan Tamansari",
    address: "Kampung Sukamaju, Kecamatan Tamansari, Kabupaten Bogor",
    organizer: "Komunitas Karsa bersama Kelompok Tani Sukamaju",
    participants: 120,
    maxParticipants: 150,
    target: "Menanam 100 bibit pohon produktif di lahan seluas 1,5 hektare",
    impact:
      "Sebanyak 108 bibit pohon berhasil ditanam dengan tingkat hidup awal 95%, melibatkan 120 relawan dan warga desa",
    achievement: "Membentuk kelompok pemantau pohon warga untuk perawatan jangka panjang",
    status: "Akan Datang",
    registration: "Pendaftaran dibuka",
    coordinator: "Dedi Kurniawan",
    contact: "0813-2211-4590",
    partner: "Kelompok Tani Sukamaju",
    volunteers: 30,
    budget: "Rp14.000.000",
    fundingSource: "Swadaya Komunitas Karsa dan bantuan Dinas Lingkungan Hidup",
    facilities: ["Bibit pohon", "Alat tanam", "Konsumsi peserta"],
    requirements: ["Menggunakan sepatu lapangan", "Membawa topi dan sarung tangan"],
    tags: ["Lingkungan", "Penghijauan", "Konservasi"],
    coverImage: COVER_LINGKUNGAN,
    images: IMAGES_LINGKUNGAN,
  },
  {
    id: "activity-003",
    title: "Workshop Pengelolaan Sampah Rumah Tangga",
    slug: "workshop-pengelolaan-sampah-rumah-tangga",
    category: "Lingkungan",
    shortDescription:
      "Melatih ibu rumah tangga memilah dan mengolah sampah organik menjadi kompos.",
    description:
      "Workshop ini digelar untuk menjawab keluhan warga RW 05 Depok yang kerap kesulitan mengelola sampah rumah tangga sebelum diangkut petugas kebersihan. Fasilitator dari bank sampah binaan Komunitas Karsa mengajarkan teknik memilah sampah organik dan anorganik, serta cara membuat kompos sederhana menggunakan ember berlubang. Peserta yang sebagian besar ibu rumah tangga dan pengurus PKK juga praktik langsung membuat eco-enzyme dari sisa buah dan sayur.",
    date: "18 Januari 2026",
    time: "09.00 WIB",
    endTime: "12.00 WIB",
    location: "Balai Warga RW 05, Kelurahan Sukmajaya",
    address: "Jl. Sukmajaya Raya No. 12, Kelurahan Sukmajaya, Depok",
    organizer: "Komunitas Karsa bersama PKK RW 05 Sukmajaya",
    participants: 47,
    maxParticipants: 50,
    target: "Melatih 40 ibu rumah tangga mempraktikkan pemilahan sampah dan pembuatan kompos",
    impact:
      "47 peserta hadir dan berhasil membuat 30 liter eco-enzyme serta 15 komposter rumah tangga dalam sehari",
    achievement: "Terbentuknya bank sampah mini di RW 05 sebagai kelanjutan program",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Sri Wahyuni",
    contact: "0857-6612-3390",
    partner: "PKK RW 05 Sukmajaya",
    volunteers: 12,
    budget: "Rp5.200.000",
    fundingSource: "Donasi warga dan CSR usaha lokal",
    facilities: ["Ember komposter", "Bahan eco-enzyme", "Modul pelatihan"],
    requirements: ["Membawa wadah sisa buah/sayur", "Menggunakan sarung tangan"],
    tags: ["Lingkungan", "Sampah", "Kompos"],
    coverImage: COVER_LINGKUNGAN,
    images: IMAGES_LINGKUNGAN,
  },
  {
    id: "activity-004",
    title: "Konservasi Mangrove Pesisir Kamal",
    slug: "konservasi-mangrove-pesisir-kamal",
    category: "Lingkungan",
    shortDescription:
      "Menanam bibit mangrove untuk melindungi garis pantai Kamal dari abrasi.",
    description:
      "Abrasi yang terus menggerus garis pantai di kawasan Kamal, Jakarta Utara, mendorong Komunitas Karsa berkolaborasi dengan kelompok nelayan setempat untuk menanam bibit mangrove jenis Rhizophora. Peserta yang terdiri dari relawan, mahasiswa, dan nelayan menyusuri tambak untuk menanam bibit di titik-titik yang telah dipetakan sebelumnya, dilengkapi edukasi singkat tentang fungsi ekosistem mangrove bagi habitat ikan dan udang.",
    date: "22 Februari 2026",
    time: "07.00 WIB",
    endTime: "10.30 WIB",
    location: "Kawasan Pesisir Kamal Muara",
    address: "Jl. Kamal Muara Raya, Kamal Muara, Jakarta Utara",
    organizer: "Komunitas Karsa bersama Kelompok Nelayan Kamal Muara",
    participants: 60,
    maxParticipants: 75,
    target: "Menanam 1.000 bibit mangrove di sepanjang 300 meter garis pantai",
    impact: "1.050 bibit mangrove tertanam dengan dukungan 60 relawan dan 12 nelayan lokal",
    achievement: "Kawasan tanam ditetapkan sebagai area konservasi swadaya warga",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Fahri Ramadhan",
    contact: "0821-9087-1123",
    partner: "Kelompok Nelayan Kamal Muara",
    volunteers: 18,
    budget: "Rp11.000.000",
    fundingSource: "Sponsor korporat dan donasi warga",
    facilities: ["Bibit mangrove", "Perahu penyeberangan", "Air minum"],
    requirements: ["Menggunakan pakaian yang boleh basah/kotor", "Membawa alas kaki lapangan"],
    tags: ["Lingkungan", "Mangrove", "Pesisir"],
    coverImage: COVER_LINGKUNGAN,
    images: IMAGES_LINGKUNGAN,
  },
  {
    id: "activity-021",
    title: "Kampanye Diet Plastik di Pasar Tradisional",
    slug: "kampanye-diet-plastik-di-pasar-tradisional",
    category: "Lingkungan",
    shortDescription:
      "Mengajak pedagang dan pembeli pasar tradisional beralih ke kemasan ramah lingkungan.",
    description:
      "Tingginya penggunaan kantong plastik sekali pakai di pasar tradisional Cibinong mendorong Komunitas Karsa menggelar kampanye diet plastik langsung di lapangan. Relawan membagikan tas belanja kain gratis kepada pembeli, mengedukasi pedagang tentang alternatif kemasan daun dan kertas, serta memasang spanduk edukasi di area pasar. Kegiatan ini juga diisi dengan penukaran sampah plastik dengan sembako sebagai insentif bagi warga.",
    date: "6 Juni 2026",
    time: "07.00 WIB",
    endTime: "10.00 WIB",
    location: "Pasar Tradisional Cibinong",
    address: "Jl. Mayor Oking Jaya Atmaja, Cibinong, Kabupaten Bogor",
    organizer: "Komunitas Karsa bersama Paguyuban Pedagang Pasar Cibinong",
    participants: 68,
    maxParticipants: 80,
    target: "Membagikan 300 tas belanja kain dan mengedukasi 100 pedagang pasar",
    impact:
      "320 tas belanja kain terdistribusi dan 110 pedagang mengikuti edukasi pengurangan plastik",
    achievement: "Sejumlah pedagang mulai konsisten menggunakan kemasan daun pisang",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Nadia Anggraini",
    contact: "0813-4470-2201",
    partner: "Paguyuban Pedagang Pasar Cibinong",
    volunteers: 20,
    budget: "Rp7.800.000",
    fundingSource: "Donasi warga dan mitra ritel lokal",
    facilities: ["Tas belanja kain", "Spanduk edukasi", "Meja penukaran sampah"],
    requirements: ["Membawa sampah plastik untuk ditukar (opsional)", "Datang tepat waktu"],
    tags: ["Lingkungan", "Plastik", "Pasar"],
    coverImage: COVER_LINGKUNGAN,
    images: IMAGES_LINGKUNGAN,
  },
  {
    id: "activity-022",
    title: "Restorasi Taman Kota dan Ruang Hijau Warga",
    slug: "restorasi-taman-kota-dan-ruang-hijau-warga",
    category: "Lingkungan",
    shortDescription:
      "Merevitalisasi taman kota yang terbengkalai menjadi ruang hijau ramah warga.",
    description:
      "Taman kota di kawasan Tangerang Selatan yang lama tidak terawat membuat fungsinya sebagai ruang publik menurun drastis. Komunitas Karsa mengajak warga sekitar, pelajar, dan dinas terkait untuk membersihkan area taman, menanam tanaman hias dan peneduh, serta memperbaiki fasilitas duduk yang rusak. Kegiatan ini diharapkan mengembalikan taman sebagai ruang interaksi sosial dan area bermain anak yang sehat.",
    date: "12 Desember 2026",
    time: "07.00 WIB",
    endTime: "11.30 WIB",
    location: "Taman Kota Serpong",
    address: "Jl. Raya Serpong, BSD, Tangerang Selatan",
    organizer: "Komunitas Karsa bersama Dinas Lingkungan Hidup Tangerang Selatan",
    participants: 90,
    maxParticipants: 110,
    target: "Merevitalisasi area taman seluas 2.000 m2 dan menanam 200 tanaman hias",
    impact: "Area taman berhasil direvitalisasi dengan 215 tanaman baru dan 10 bangku taman diperbaiki",
    achievement: "Taman kembali ramai dikunjungi warga untuk olahraga pagi dan bermain anak",
    status: "Akan Datang",
    registration: "Pendaftaran dibuka",
    coordinator: "Yoga Pratama",
    contact: "0838-1290-6675",
    partner: "Dinas Lingkungan Hidup Tangerang Selatan",
    volunteers: 26,
    budget: "Rp16.500.000",
    fundingSource: "Anggaran dinas dan donasi warga",
    facilities: ["Tanaman hias", "Alat berkebun", "Konsumsi peserta"],
    requirements: ["Menggunakan pakaian nyaman", "Membawa sarung tangan berkebun"],
    tags: ["Lingkungan", "Taman", "Ruang Hijau"],
    coverImage: COVER_LINGKUNGAN,
    images: IMAGES_LINGKUNGAN,
  },

  // ===================== SOSIAL (6) =====================
  {
    id: "activity-005",
    title: "Pembagian Sembako untuk Warga Terdampak Banjir",
    slug: "pembagian-sembako-untuk-warga-terdampak-banjir",
    category: "Sosial",
    shortDescription: "Menyalurkan paket sembako bagi warga yang rumahnya terendam banjir.",
    description:
      "Banjir yang merendam permukiman padat penduduk di bantaran Kali Sunter membuat puluhan keluarga kehilangan akses ke kebutuhan pokok. Komunitas Karsa menggalang donasi dari warga sekitar dan mitra usaha lokal untuk dikemas menjadi paket sembako berisi beras, minyak goreng, dan mi instan. Relawan turun langsung mendata keluarga terdampak dan mendistribusikan bantuan dari pintu ke pintu agar tepat sasaran.",
    date: "3 Maret 2026",
    time: "08.00 WIB",
    endTime: "12.00 WIB",
    location: "RW 03 Kelurahan Cipinang Melayu",
    address: "Jl. Cipinang Melayu Raya, Jakarta Timur",
    organizer: "Komunitas Karsa bersama RT/RW setempat",
    participants: 38,
    maxParticipants: 45,
    target: "Menyalurkan 150 paket sembako kepada keluarga terdampak banjir",
    impact: "150 paket sembako tersalurkan kepada 150 keluarga, dibantu oleh 38 relawan lapangan",
    achievement: "Seluruh keluarga terdampak menerima bantuan dalam waktu kurang dari 4 jam",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Wulan Sari",
    contact: "0812-7743-9021",
    partner: "RT/RW Kelurahan Cipinang Melayu",
    volunteers: 15,
    budget: "Rp22.000.000",
    fundingSource: "Donasi warga dan mitra usaha lokal",
    facilities: ["Paket sembako", "Kendaraan distribusi", "Meja pendataan"],
    requirements: ["Membawa kartu keluarga (untuk penerima)", "Mengisi formulir pendaftaran"],
    tags: ["Sosial", "Bencana", "Sembako"],
    coverImage: COVER_SOSIAL,
    images: IMAGES_SOSIAL,
  },
  {
    id: "activity-006",
    title: "Donor Darah Peduli Sesama",
    slug: "donor-darah-peduli-sesama",
    category: "Sosial",
    shortDescription: "Menggalang stok darah untuk PMI melalui kegiatan donor darah massal.",
    description:
      "Menyusul menipisnya stok darah di PMI Kota Bogor, Komunitas Karsa berinisiatif menggelar kegiatan donor darah terbuka untuk umum, berkolaborasi dengan PMI dan sebuah rumah sakit swasta yang menyediakan tenaga medis serta unit mobil donor darah. Selain donor darah, panitia juga menyediakan sesi konsultasi kesehatan singkat serta pemeriksaan tekanan darah gratis bagi seluruh peserta yang hadir.",
    date: "14 April 2026",
    time: "08.30 WIB",
    endTime: "13.00 WIB",
    location: "Aula Kelurahan Baranangsiang",
    address: "Jl. Baranangsiang No. 8, Bogor Timur, Bogor",
    organizer: "Komunitas Karsa bersama PMI Kota Bogor",
    participants: 96,
    maxParticipants: 120,
    target: "Mengumpulkan minimal 80 kantong darah dari peserta yang memenuhi syarat",
    impact: "96 pendaftar hadir dan 74 kantong darah berhasil dikumpulkan untuk stok PMI Kota Bogor",
    achievement: "Menjadi kegiatan donor darah dengan partisipasi tertinggi di wilayah Bogor Timur tahun ini",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Bagus Setiawan",
    contact: "0819-3345-0087",
    partner: "PMI Kota Bogor",
    volunteers: 22,
    budget: "Rp9.500.000",
    fundingSource: "Donasi warga dan dukungan rumah sakit mitra",
    facilities: ["Unit mobil donor darah", "Konsumsi peserta", "Perlengkapan P3K"],
    requirements: ["Membawa kartu identitas", "Dalam kondisi sehat dan cukup tidur"],
    tags: ["Sosial", "Kesehatan", "Donor Darah"],
    coverImage: COVER_SOSIAL,
    images: IMAGES_SOSIAL,
  },
  {
    id: "activity-007",
    title: "Pasar Karya Warga",
    slug: "pasar-karya-warga",
    category: "Sosial",
    shortDescription:
      "Menghadirkan pasar murah kebutuhan pokok sekaligus panggung produk UMKM warga.",
    description:
      "Pasar Karya Warga digelar sebagai respons atas kenaikan harga kebutuhan pokok menjelang hari besar keagamaan yang memberatkan warga berpenghasilan rendah di sekitar Depok. Selain menjual sembako dengan harga di bawah pasaran, acara ini juga menjadi ruang promosi bagi pelaku UMKM lokal untuk memamerkan produk olahan makanan dan kerajinan tangan mereka, diiringi pertunjukan musik dari pelajar setempat.",
    date: "9 Mei 2026",
    time: "07.00 WIB",
    endTime: "13.00 WIB",
    location: "Lapangan Kelurahan Beji",
    address: "Jl. Beji Raya, Kecamatan Beji, Depok",
    organizer: "Komunitas Karsa bersama Paguyuban UMKM Beji",
    participants: 210,
    maxParticipants: 250,
    target: "Menjual 500 paket sembako subsidi dan memfasilitasi 20 pelaku UMKM",
    impact:
      "480 paket sembako terjual habis dan 22 UMKM berhasil memamerkan produknya kepada lebih dari 200 pengunjung",
    achievement: "Omzet gabungan pelaku UMKM meningkat lebih dari 2 kali lipat dari hari biasa",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Melati Putri",
    contact: "0857-1120-8834",
    partner: "Paguyuban UMKM Beji",
    volunteers: 28,
    budget: "Rp18.000.000",
    fundingSource: "Swadaya UMKM dan donasi warga",
    facilities: ["Tenda lapak", "Sound system", "Meja pendaftaran UMKM"],
    requirements: ["Mendaftar lapak melalui panitia", "Membawa perlengkapan dagang sendiri"],
    tags: ["Sosial", "UMKM", "Pasar Murah"],
    coverImage: COVER_SOSIAL,
    images: IMAGES_SOSIAL,
  },
  {
    id: "activity-008",
    title: "Bakti Sosial untuk Lansia Mandiri",
    slug: "bakti-sosial-untuk-lansia-mandiri",
    category: "Sosial",
    shortDescription:
      "Memberi perhatian dan bantuan kebutuhan sehari-hari bagi lansia yang tinggal sendiri.",
    description:
      "Banyak lansia di kawasan padat penduduk Jakarta Selatan tinggal sendiri tanpa pendamping keluarga, sehingga rentan mengalami kesepian dan kesulitan memenuhi kebutuhan sehari-hari. Komunitas Karsa bersama karang taruna setempat mendatangi rumah-rumah lansia untuk memberikan paket kebutuhan pokok, memeriksa kondisi kesehatan dasar, serta sekadar menemani mengobrol sebagai bentuk kepedulian terhadap kelompok rentan di lingkungan perkotaan.",
    date: "27 Mei 2026",
    time: "09.00 WIB",
    endTime: "12.00 WIB",
    location: "Kelurahan Pela Mampang",
    address: "Jl. Mampang Prapatan Raya, Jakarta Selatan",
    organizer: "Komunitas Karsa bersama Karang Taruna Pela Mampang",
    participants: 30,
    maxParticipants: 35,
    target: "Mengunjungi dan membantu 25 lansia yang tinggal sendiri di wilayah tersebut",
    impact:
      "28 lansia berhasil dikunjungi dan menerima paket kebutuhan pokok serta pemeriksaan kesehatan dasar",
    achievement: "Terbentuknya jadwal kunjungan rutin bulanan untuk lansia binaan",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Indra Gunawan",
    contact: "0813-8890-2245",
    partner: "Karang Taruna Pela Mampang",
    volunteers: 14,
    budget: "Rp6.400.000",
    fundingSource: "Donasi warga",
    facilities: ["Paket kebutuhan pokok", "Alat cek kesehatan dasar", "Kendaraan kunjungan"],
    requirements: ["Membawa data lansia sasaran", "Bersikap sabar dan ramah"],
    tags: ["Sosial", "Lansia", "Kepedulian"],
    coverImage: COVER_SOSIAL,
    images: IMAGES_SOSIAL,
  },
  {
    id: "activity-023",
    title: "Dapur Berbagi untuk Buruh Harian",
    slug: "dapur-berbagi-untuk-buruh-harian",
    category: "Sosial",
    shortDescription:
      "Menyediakan makan siang gratis bagi buruh harian dan pekerja informal di kawasan industri.",
    description:
      "Banyak buruh harian dan pekerja informal di kawasan industri Bekasi yang harus mengirit pengeluaran makan demi memenuhi kebutuhan lain. Komunitas Karsa menghadirkan Dapur Berbagi berupa dapur umum keliling yang menyediakan makan siang bergizi secara gratis. Relawan memasak menggunakan bahan hasil donasi warga dan pedagang pasar, kemudian mendistribusikannya langsung ke titik-titik kumpul buruh.",
    date: "3 Juli 2026",
    time: "11.00 WIB",
    endTime: "14.00 WIB",
    location: "Kawasan Industri MM2100",
    address: "Jl. Kalimantan, Kawasan Industri MM2100, Cikarang Barat, Bekasi",
    organizer: "Komunitas Karsa bersama Serikat Pekerja Informal Bekasi",
    participants: 55,
    maxParticipants: 60,
    target: "Membagikan 400 porsi makan siang gratis bagi buruh harian",
    impact: "430 porsi makan siang berhasil dibagikan kepada buruh dan pekerja informal",
    achievement: "Program dilanjutkan menjadi kegiatan rutin dua mingguan",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Fitriani Lestari",
    contact: "0821-6650-1147",
    partner: "Serikat Pekerja Informal Bekasi",
    volunteers: 18,
    budget: "Rp10.200.000",
    fundingSource: "Donasi warga dan pedagang pasar",
    facilities: ["Dapur umum keliling", "Alat masak", "Kotak makan"],
    requirements: ["Membawa alat makan sendiri (opsional)", "Antre sesuai arahan relawan"],
    tags: ["Sosial", "Dapur Berbagi", "Buruh"],
    coverImage: COVER_SOSIAL,
    images: IMAGES_SOSIAL,
  },
  {
    id: "activity-024",
    title: "Santunan Yatim dan Dhuafa Ramadan",
    slug: "santunan-yatim-dan-dhuafa-ramadan",
    category: "Sosial",
    shortDescription:
      "Memberikan santunan kepada anak yatim dan keluarga dhuafa menjelang bulan suci Ramadan.",
    description:
      "Menyambut bulan suci Ramadan, Komunitas Karsa menggalang donasi dari warga dan donatur untuk disalurkan kepada anak yatim dan keluarga dhuafa di wilayah Tangerang. Santunan berupa dana tunai, sembako, dan perlengkapan ibadah dibagikan dalam acara buka puasa bersama yang turut mengundang tokoh masyarakat setempat untuk memberikan tausiah singkat.",
    date: "20 Maret 2026",
    time: "15.30 WIB",
    endTime: "18.30 WIB",
    location: "Masjid Al-Ikhlas, Kelurahan Cipondoh",
    address: "Jl. Cipondoh Makmur, Cipondoh, Tangerang",
    organizer: "Komunitas Karsa bersama DKM Masjid Al-Ikhlas",
    participants: 140,
    maxParticipants: 160,
    target: "Menyantuni 100 anak yatim dan keluarga dhuafa",
    impact: "115 anak yatim dan keluarga dhuafa menerima santunan tunai dan paket sembako",
    achievement: "Total dana santunan terkumpul melebihi target sebesar 20 persen",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Ahmad Zulkarnain",
    contact: "0812-5567-9034",
    partner: "DKM Masjid Al-Ikhlas Cipondoh",
    volunteers: 25,
    budget: "Rp35.000.000",
    fundingSource: "Donasi warga dan donatur individu",
    facilities: ["Paket santunan", "Menu buka puasa", "Sound system"],
    requirements: ["Data penerima disiapkan panitia RW/DKM", "Membawa kartu identitas"],
    tags: ["Sosial", "Santunan", "Ramadan"],
    coverImage: COVER_SOSIAL,
    images: IMAGES_SOSIAL,
  },

  // ===================== EDUKASI (6) =====================
  {
    id: "activity-009",
    title: "Ruang Belajar Akhir Pekan",
    slug: "ruang-belajar-akhir-pekan",
    category: "Edukasi",
    shortDescription:
      "Membuka kelas belajar gratis bagi anak-anak di permukiman padat setiap akhir pekan.",
    description:
      "Ruang Belajar Akhir Pekan hadir untuk anak-anak di kawasan padat penduduk yang minim akses bimbingan belajar tambahan di luar sekolah. Relawan mahasiswa dan guru muda bergiliran mengajarkan calistung, matematika dasar, hingga bahasa Inggris dengan metode belajar sambil bermain, dilengkapi sesi mendongeng untuk menumbuhkan minat baca sejak dini.",
    date: "14 Juni 2026",
    time: "09.00 WIB",
    endTime: "11.30 WIB",
    location: "Balai RW 02, Kelurahan Kalibaru",
    address: "Jl. Kalibaru Timur, Kecamatan Cilodong, Depok",
    organizer: "Komunitas Karsa bersama relawan mahasiswa",
    participants: 42,
    maxParticipants: 50,
    target: "Memberikan pendampingan belajar rutin bagi 35 anak usia sekolah dasar",
    impact: "42 anak mengikuti kegiatan secara konsisten setiap pekan, dengan 10 relawan pengajar terlibat",
    achievement: "Rata-rata nilai ulangan harian peserta meningkat setelah tiga bulan program",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Citra Ayu Lestari",
    contact: "0857-9012-4456",
    partner: "Relawan Mahasiswa Peduli Pendidikan",
    volunteers: 10,
    budget: "Rp4.500.000",
    fundingSource: "Donasi warga",
    facilities: ["Alat tulis", "Buku bacaan", "Modul pelatihan"],
    requirements: ["Membawa alat tulis pribadi", "Datang tepat waktu"],
    tags: ["Edukasi", "Anak", "Belajar"],
    coverImage: COVER_EDUKASI,
    images: IMAGES_EDUKASI,
  },
  {
    id: "activity-010",
    title: "Pelatihan Literasi Digital untuk Guru",
    slug: "pelatihan-literasi-digital-untuk-guru",
    category: "Edukasi",
    shortDescription:
      "Membekali guru sekolah dasar dengan keterampilan mengajar menggunakan media digital.",
    description:
      "Banyak guru sekolah dasar di daerah pinggiran kota masih kesulitan mengadaptasi metode pembelajaran berbasis digital pasca perubahan kurikulum. Komunitas Karsa menggandeng praktisi pendidikan untuk memberikan pelatihan penggunaan aplikasi presentasi interaktif, kuis daring, dan pembuatan materi ajar berbasis video sederhana, ditutup dengan simulasi mengajar menggunakan perangkat yang telah dipelajari.",
    date: "20 Juli 2026",
    time: "08.00 WIB",
    endTime: "15.00 WIB",
    location: "SDN 02 Cibinong",
    address: "Jl. Raya Cibinong No. 45, Cibinong, Kabupaten Bogor",
    organizer: "Komunitas Karsa bersama Dinas Pendidikan setempat",
    participants: 55,
    maxParticipants: 60,
    target: "Melatih 50 guru sekolah dasar dalam pemanfaatan media ajar digital",
    impact: "55 guru dari 12 sekolah mengikuti pelatihan dan menghasilkan 20 modul ajar digital baru",
    achievement: "Modul ajar digital yang dihasilkan diadopsi oleh gugus sekolah setempat",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Budi Hartono",
    contact: "0813-7789-0021",
    partner: "Dinas Pendidikan Kabupaten Bogor",
    volunteers: 8,
    budget: "Rp12.500.000",
    fundingSource: "Anggaran dinas dan donasi mitra pendidikan",
    facilities: ["Laptop dan proyektor", "Modul pelatihan", "Konsumsi peserta"],
    requirements: ["Membawa laptop pribadi", "Merupakan guru aktif"],
    tags: ["Edukasi", "Guru", "Literasi Digital"],
    coverImage: COVER_EDUKASI,
    images: IMAGES_EDUKASI,
  },
  {
    id: "activity-011",
    title: "Kelas Kreatif Anak: Seni dari Barang Bekas",
    slug: "kelas-kreatif-anak-seni-dari-barang-bekas",
    category: "Edukasi",
    shortDescription: "Mengajak anak-anak berkreasi membuat karya seni dari sampah anorganik.",
    description:
      "Kelas kreatif ini dirancang untuk menumbuhkan kepekaan lingkungan sekaligus kreativitas anak melalui kegiatan mendaur ulang barang bekas seperti botol plastik dan kardus menjadi mainan dan hiasan. Relawan dari komunitas seni lokal memandu anak-anak membuat karya secara berkelompok, kemudian karya terbaik dipamerkan di akhir acara untuk menanamkan nilai kreativitas dan kepedulian lingkungan sejak dini.",
    date: "8 Agustus 2026",
    time: "13.00 WIB",
    endTime: "16.00 WIB",
    location: "Taman Baca RW 07, Kelurahan Cimanggis",
    address: "Jl. Raya Cimanggis No. 21, Depok",
    organizer: "Komunitas Karsa bersama Komunitas Seni Cimanggis",
    participants: 65,
    maxParticipants: 70,
    target: "Melibatkan 60 anak dalam pembuatan karya daur ulang secara berkelompok",
    impact:
      "65 anak berpartisipasi dan menghasilkan lebih dari 40 karya daur ulang yang dipamerkan kepada warga",
    achievement: "Karya terbaik dipajang permanen di Taman Baca RW 07",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Sinta Maharani",
    contact: "0812-4432-6675",
    partner: "Komunitas Seni Cimanggis",
    volunteers: 16,
    budget: "Rp6.700.000",
    fundingSource: "Donasi warga dan komunitas seni",
    facilities: ["Bahan daur ulang", "Alat prakarya", "Konsumsi anak"],
    requirements: ["Membawa barang bekas dari rumah", "Didampingi orang tua/wali"],
    tags: ["Edukasi", "Anak", "Kreativitas"],
    coverImage: COVER_EDUKASI,
    images: IMAGES_EDUKASI,
  },
  {
    id: "activity-012",
    title: "Gerakan Membaca untuk Semua",
    slug: "gerakan-membaca-untuk-semua",
    category: "Edukasi",
    shortDescription: "Mendirikan pojok baca keliling untuk menumbuhkan minat baca anak di ruang publik.",
    description:
      "Rendahnya minat baca anak-anak di taman kota mendorong Komunitas Karsa menghadirkan pojok baca keliling berupa rak buku portabel yang dibawa menggunakan sepeda. Relawan literasi membacakan cerita bergambar dan mengajak anak-anak berdiskusi tentang isi buku setelah selesai membaca. Buku-buku yang digunakan merupakan hasil donasi warga dan penerbit yang peduli literasi anak.",
    date: "21 September 2026",
    time: "15.00 WIB",
    endTime: "17.30 WIB",
    location: "Taman Kota 1, Kota Wisata, Cibubur",
    address: "Jl. Alternatif Cibubur, Kota Wisata, Jawa Barat",
    organizer: "Komunitas Karsa bersama relawan literasi",
    participants: 58,
    maxParticipants: 65,
    target: "Menjangkau 50 anak untuk membaca dan berdiskusi buku dalam satu sesi",
    impact:
      "58 anak hadir membaca buku, dengan 120 judul buku donasi berhasil dihimpun untuk pojok baca keliling",
    achievement: "Pojok baca keliling kini rutin hadir dua kali sebulan di lokasi berbeda",
    status: "Akan Datang",
    registration: "Pendaftaran dibuka",
    coordinator: "Reza Fadillah",
    contact: "0857-3321-0098",
    partner: "Komunitas Literasi Cibubur",
    volunteers: 12,
    budget: "Rp3.800.000",
    fundingSource: "Donasi buku dan dana warga",
    facilities: ["Rak buku portabel", "Tikar baca", "Koleksi buku anak"],
    requirements: ["Anak didampingi orang tua/wali", "Menjaga kebersihan buku"],
    tags: ["Edukasi", "Literasi", "Anak"],
    coverImage: COVER_EDUKASI,
    images: IMAGES_EDUKASI,
  },
  {
    id: "activity-025",
    title: "Perpustakaan Keliling Desa Tertinggal",
    slug: "perpustakaan-keliling-desa-tertinggal",
    category: "Edukasi",
    shortDescription:
      "Menghadirkan akses buku bacaan bagi anak-anak di desa yang jauh dari perpustakaan.",
    description:
      "Desa-desa di wilayah pinggiran Kabupaten Bogor umumnya belum memiliki akses perpustakaan yang memadai. Komunitas Karsa menghadirkan perpustakaan keliling menggunakan mobil boks yang dimodifikasi menjadi rak buku berjalan, mengunjungi desa secara bergiliran setiap bulan. Selain meminjamkan buku, relawan juga mengadakan sesi permainan edukatif dan lomba mewarnai bagi anak-anak desa.",
    date: "30 Mei 2026",
    time: "09.00 WIB",
    endTime: "12.00 WIB",
    location: "Balai Desa Cileungsi Kidul",
    address: "Jl. Raya Cileungsi Kidul, Kabupaten Bogor, Jawa Barat",
    organizer: "Komunitas Karsa bersama Pemerintah Desa Cileungsi Kidul",
    participants: 75,
    maxParticipants: 90,
    target: "Menjangkau 60 anak desa dengan layanan pinjam buku dan kegiatan literasi",
    impact: "75 anak dari 3 dusun mengikuti kegiatan dan 200 buku dipinjamkan dalam sehari",
    achievement: "Desa Cileungsi Kidul kini masuk rute tetap kunjungan bulanan perpustakaan keliling",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Putri Ramadhani",
    contact: "0812-9087-3345",
    partner: "Pemerintah Desa Cileungsi Kidul",
    volunteers: 14,
    budget: "Rp9.000.000",
    fundingSource: "Donasi buku dan dana operasional komunitas",
    facilities: ["Mobil perpustakaan keliling", "Koleksi buku anak", "Alat mewarnai"],
    requirements: ["Anak didampingi orang tua/wali", "Mengembalikan buku tepat waktu"],
    tags: ["Edukasi", "Perpustakaan Keliling", "Desa"],
    coverImage: COVER_EDUKASI,
    images: IMAGES_EDUKASI,
  },
  {
    id: "activity-026",
    title: "Workshop Komputer Dasar untuk Pemuda",
    slug: "workshop-komputer-dasar-untuk-pemuda",
    category: "Edukasi",
    shortDescription:
      "Melatih pemuda putus sekolah dan pencari kerja menguasai keterampilan komputer dasar.",
    description:
      "Minimnya keterampilan komputer dasar menjadi salah satu hambatan pemuda di wilayah Tangerang Selatan dalam melamar pekerjaan. Komunitas Karsa bekerja sama dengan lembaga pelatihan kerja lokal menyelenggarakan workshop penggunaan aplikasi perkantoran, dasar internet, dan pembuatan surat lamaran digital. Peserta juga mendapatkan sertifikat pelatihan yang dapat dilampirkan saat melamar kerja.",
    date: "19 Desember 2026",
    time: "09.00 WIB",
    endTime: "15.00 WIB",
    location: "Balai Latihan Kerja Ciputat",
    address: "Jl. Aria Putra, Ciputat, Tangerang Selatan",
    organizer: "Komunitas Karsa bersama Lembaga Pelatihan Kerja Ciputat",
    participants: 48,
    maxParticipants: 50,
    target: "Melatih 45 pemuda dalam keterampilan komputer dasar dan pembuatan CV digital",
    impact: "48 peserta menyelesaikan pelatihan dan menerima sertifikat kompetensi dasar",
    achievement: "12 peserta berhasil mendapatkan pekerjaan dalam dua bulan setelah pelatihan",
    status: "Akan Datang",
    registration: "Pendaftaran dibuka",
    coordinator: "Andika Pratama",
    contact: "0813-6654-2298",
    partner: "Lembaga Pelatihan Kerja Ciputat",
    volunteers: 10,
    budget: "Rp13.200.000",
    fundingSource: "Bantuan lembaga pelatihan dan donasi mitra",
    facilities: ["Unit komputer", "Modul pelatihan", "Sertifikat peserta"],
    requirements: ["Usia 17-30 tahun", "Membawa kartu identitas"],
    tags: ["Edukasi", "Pelatihan Kerja", "Pemuda"],
    coverImage: COVER_EDUKASI,
    images: IMAGES_EDUKASI,
  },

  // ===================== KEMANUSIAAN (6) =====================
  {
    id: "activity-013",
    title: "Bantuan Tanggap Darurat Longsor Cisarua",
    slug: "bantuan-tanggap-darurat-longsor-cisarua",
    category: "Kemanusiaan",
    shortDescription: "Menyalurkan bantuan darurat bagi korban longsor di kawasan Cisarua.",
    description:
      "Longsor yang menerjang permukiman di lereng Cisarua memaksa puluhan keluarga mengungsi ke tempat yang lebih aman. Komunitas Karsa bergerak cepat mendirikan posko bantuan darurat berisi tenda, selimut, obat-obatan, dan makanan siap saji. Relawan juga membantu proses evakuasi barang milik warga serta memberikan dukungan psikososial awal bagi anak-anak yang mengalami trauma akibat kejadian tersebut.",
    date: "15 Oktober 2026",
    time: "06.00 WIB",
    endTime: "18.00 WIB",
    location: "Kampung Ciburial, Kecamatan Cisarua",
    address: "Kampung Ciburial, Kecamatan Cisarua, Kabupaten Bogor",
    organizer: "Komunitas Karsa bersama BPBD Kabupaten Bogor",
    participants: 70,
    maxParticipants: 85,
    target: "Mendirikan posko darurat dan melayani kebutuhan dasar 40 keluarga terdampak",
    impact:
      "45 keluarga menerima bantuan darurat, dengan 70 relawan turun langsung dalam proses evakuasi dan distribusi logistik",
    achievement: "Posko darurat berhasil didirikan kurang dari 3 jam setelah kejadian",
    status: "Akan Datang",
    registration: "Pendaftaran dibuka",
    coordinator: "Hendra Wijaya",
    contact: "0812-2290-7761",
    partner: "BPBD Kabupaten Bogor",
    volunteers: 32,
    budget: "Rp25.000.000",
    fundingSource: "Dana tanggap darurat dan donasi warga",
    facilities: ["Posko bantuan", "Obat-obatan dasar", "Perlengkapan darurat"],
    requirements: ["Membawa kartu identitas", "Mengikuti arahan koordinator lapangan"],
    tags: ["Kemanusiaan", "Bencana", "Tanggap Darurat"],
    coverImage: COVER_KEMANUSIAAN,
    images: IMAGES_KEMANUSIAAN,
  },
  {
    id: "activity-014",
    title: "Peduli Anak Yatim Nusantara",
    slug: "peduli-anak-yatim-nusantara",
    category: "Kemanusiaan",
    shortDescription:
      "Memberikan santunan dan pendampingan pendidikan bagi anak yatim di panti asuhan binaan.",
    description:
      "Program ini digagas untuk memberikan perhatian berkelanjutan kepada anak-anak yatim yang tinggal di panti asuhan mitra Komunitas Karsa. Selain memberikan santunan berupa dana pendidikan dan perlengkapan sekolah, relawan juga mengadakan sesi motivasi dan permainan edukatif untuk menjaga semangat belajar anak-anak, dengan harapan dapat berlanjut menjadi program pendampingan jangka panjang.",
    date: "8 November 2026",
    time: "09.00 WIB",
    endTime: "13.00 WIB",
    location: "Panti Asuhan Nurul Iman, Parung",
    address: "Jl. Parung Raya, Parung, Kabupaten Bogor",
    organizer: "Komunitas Karsa bersama donatur individu",
    participants: 40,
    maxParticipants: 45,
    target: "Memberikan santunan pendidikan kepada 35 anak yatim di panti asuhan",
    impact: "38 anak menerima santunan dana pendidikan dan perlengkapan sekolah senilai total Rp45 juta",
    achievement: "Program pendampingan diperpanjang menjadi kegiatan tahunan",
    status: "Akan Datang",
    registration: "Pendaftaran dibuka",
    coordinator: "Dewi Anjani",
    contact: "0857-8821-5567",
    partner: "Panti Asuhan Nurul Iman",
    volunteers: 20,
    budget: "Rp45.000.000",
    fundingSource: "Donatur individu dan donasi warga",
    facilities: ["Perlengkapan sekolah", "Konsumsi anak", "Permainan edukatif"],
    requirements: ["Data anak disiapkan pihak panti", "Relawan wajib mengikuti briefing"],
    tags: ["Kemanusiaan", "Anak Yatim", "Pendidikan"],
    coverImage: COVER_KEMANUSIAAN,
    images: IMAGES_KEMANUSIAAN,
  },
  {
    id: "activity-015",
    title: "Layanan Kesehatan Gratis Keliling",
    slug: "layanan-kesehatan-gratis-keliling",
    category: "Kemanusiaan",
    shortDescription: "Menghadirkan pemeriksaan kesehatan gratis bagi warga yang sulit mengakses puskesmas.",
    description:
      "Keterbatasan akses layanan kesehatan di permukiman padat mendorong Komunitas Karsa menggandeng tenaga medis sukarela untuk menggelar layanan kesehatan keliling. Warga dapat memeriksakan tekanan darah, gula darah, dan kolesterol secara gratis, serta berkonsultasi langsung dengan dokter umum. Obat-obatan ringan turut dibagikan kepada peserta yang membutuhkan sesuai anjuran dokter.",
    date: "29 November 2026",
    time: "08.00 WIB",
    endTime: "12.00 WIB",
    location: "Posyandu RW 04, Kelurahan Mekarjaya",
    address: "Jl. Mekarjaya Raya, Kecamatan Sukmajaya, Depok",
    organizer: "Komunitas Karsa bersama relawan tenaga medis",
    participants: 130,
    maxParticipants: 150,
    target: "Melayani pemeriksaan kesehatan gratis bagi 100 warga lanjut usia dan prasejahtera",
    impact: "130 warga terlayani pemeriksaan kesehatan, dengan 40 di antaranya dirujuk untuk pemeriksaan lanjutan",
    achievement: "Menjadi layanan kesehatan keliling dengan jumlah peserta terbanyak sepanjang tahun",
    status: "Akan Datang",
    registration: "Pendaftaran dibuka",
    coordinator: "dr. Anisa Rahmawati",
    contact: "0813-2298-6612",
    partner: "Ikatan Relawan Medis Depok",
    volunteers: 24,
    budget: "Rp15.800.000",
    fundingSource: "Donasi warga dan mitra kesehatan",
    facilities: ["Alat cek kesehatan", "Obat-obatan dasar", "Meja pendaftaran"],
    requirements: ["Membawa kartu identitas", "Datang sesuai jadwal antrean"],
    tags: ["Kemanusiaan", "Kesehatan", "Layanan Gratis"],
    coverImage: COVER_KEMANUSIAAN,
    images: IMAGES_KEMANUSIAAN,
  },
  {
    id: "activity-016",
    title: "Donasi Pakaian Layak Pakai",
    slug: "donasi-pakaian-layak-pakai",
    category: "Kemanusiaan",
    shortDescription: "Mengumpulkan dan menyalurkan pakaian layak pakai bagi warga prasejahtera.",
    description:
      "Menumpuknya pakaian layak pakai yang tidak terpakai di rumah warga mendorong Komunitas Karsa membuka program donasi pakaian yang kemudian disortir dan dibersihkan sebelum disalurkan. Kegiatan ini menyasar warga prasejahtera di daerah pinggiran Jakarta yang membutuhkan pakaian untuk kebutuhan sehari-hari maupun menghadapi musim hujan, dilengkapi bazar pakaian gratis agar warga dapat memilih sendiri pakaian yang sesuai kebutuhan.",
    date: "13 Desember 2026",
    time: "08.00 WIB",
    endTime: "11.00 WIB",
    location: "Lapangan Kelurahan Marunda",
    address: "Jl. Marunda Baru, Cilincing, Jakarta Utara",
    organizer: "Komunitas Karsa bersama relawan lingkungan RW",
    participants: 45,
    maxParticipants: 55,
    target: "Mengumpulkan dan menyalurkan 1.000 potong pakaian layak pakai",
    impact: "1.150 potong pakaian berhasil dikumpulkan dan disalurkan kepada lebih dari 300 warga",
    achievement: "Program donasi pakaian menjadi kegiatan rutin triwulanan komunitas",
    status: "Akan Datang",
    registration: "Pendaftaran dibuka",
    coordinator: "Lestari Handayani",
    contact: "0821-4471-9903",
    partner: "Relawan Lingkungan RW Marunda",
    volunteers: 19,
    budget: "Rp4.900.000",
    fundingSource: "Donasi warga",
    facilities: ["Meja sortir pakaian", "Rak bazar", "Kantong pakaian"],
    requirements: ["Pakaian dalam kondisi bersih dan layak pakai", "Membawa kartu identitas untuk penerima"],
    tags: ["Kemanusiaan", "Donasi Pakaian", "Bazar"],
    coverImage: COVER_KEMANUSIAAN,
    images: IMAGES_KEMANUSIAAN,
  },
  {
    id: "activity-027",
    title: "Bantuan Kebutuhan Dasar Keluarga Prasejahtera",
    slug: "bantuan-kebutuhan-dasar-keluarga-prasejahtera",
    category: "Kemanusiaan",
    shortDescription:
      "Menyalurkan bantuan kebutuhan dasar bagi keluarga prasejahtera yang terdata di wilayah Bogor.",
    description:
      "Berdasarkan hasil pendataan bersama RT/RW, ditemukan sejumlah keluarga prasejahtera di wilayah Bogor yang kesulitan memenuhi kebutuhan dasar seperti pangan dan kebutuhan bayi. Komunitas Karsa menyalurkan bantuan berupa sembako, susu, dan popok bayi secara langsung ke rumah masing-masing keluarga, disertai pendataan lanjutan untuk program bantuan berkelanjutan.",
    date: "10 Agustus 2026",
    time: "09.00 WIB",
    endTime: "13.00 WIB",
    location: "Kelurahan Kedung Waringin",
    address: "Jl. Kedung Waringin, Kecamatan Tanah Sareal, Bogor",
    organizer: "Komunitas Karsa bersama RT/RW Kedung Waringin",
    participants: 32,
    maxParticipants: 40,
    target: "Menyalurkan bantuan kebutuhan dasar kepada 50 keluarga prasejahtera",
    impact: "54 keluarga menerima bantuan sembako, susu, dan popok bayi",
    achievement: "Data keluarga prasejahtera diperbarui untuk program pendampingan lanjutan",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Herlina Susanti",
    contact: "0857-2298-1145",
    partner: "RT/RW Kedung Waringin",
    volunteers: 16,
    budget: "Rp13.500.000",
    fundingSource: "Donasi warga dan donatur individu",
    facilities: ["Paket kebutuhan dasar", "Kendaraan distribusi", "Meja pendataan"],
    requirements: ["Data keluarga disiapkan RT/RW", "Membawa kartu keluarga"],
    tags: ["Kemanusiaan", "Keluarga Prasejahtera", "Bantuan Dasar"],
    coverImage: COVER_KEMANUSIAAN,
    images: IMAGES_KEMANUSIAAN,
  },
  {
    id: "activity-028",
    title: "Aksi Tanggap Darurat Banjir Bekasi",
    slug: "aksi-tanggap-darurat-banjir-bekasi",
    category: "Kemanusiaan",
    shortDescription: "Mengevakuasi dan membantu warga terdampak banjir di wilayah Bekasi.",
    description:
      "Curah hujan tinggi menyebabkan sejumlah permukiman di Bekasi terendam banjir hingga mencapai ketinggian satu meter. Komunitas Karsa bersama relawan gabungan turun langsung membantu proses evakuasi warga, mendirikan dapur umum, dan menyalurkan bantuan logistik berupa makanan siap saji, air bersih, dan obat-obatan ke titik pengungsian.",
    date: "20 Oktober 2026",
    time: "05.00 WIB",
    endTime: "17.00 WIB",
    location: "Perumahan Pondok Gede Permai",
    address: "Jl. Raya Jatiasih, Pondok Gede Permai, Bekasi",
    organizer: "Komunitas Karsa bersama Relawan Gabungan Bekasi",
    participants: 88,
    maxParticipants: 100,
    target: "Mengevakuasi dan melayani kebutuhan dasar 60 keluarga terdampak banjir",
    impact: "72 keluarga berhasil dievakuasi dan menerima bantuan logistik darurat",
    achievement: "Dapur umum darurat beroperasi selama tiga hari berturut-turut",
    status: "Akan Datang",
    registration: "Pendaftaran dibuka",
    coordinator: "Taufik Hidayat",
    contact: "0812-3390-5567",
    partner: "Relawan Gabungan Bekasi",
    volunteers: 36,
    budget: "Rp28.000.000",
    fundingSource: "Dana tanggap darurat dan donasi warga",
    facilities: ["Perahu evakuasi", "Dapur umum darurat", "Posko kesehatan"],
    requirements: ["Mampu berenang atau menggunakan pelampung", "Mengikuti arahan koordinator lapangan"],
    tags: ["Kemanusiaan", "Banjir", "Evakuasi"],
    coverImage: COVER_KEMANUSIAAN,
    images: IMAGES_KEMANUSIAAN,
  },

  // ===================== KOMUNITAS (6) =====================
  {
    id: "activity-017",
    title: "Pemberdayaan UMKM Warung Kampung",
    slug: "pemberdayaan-umkm-warung-kampung",
    category: "Komunitas",
    shortDescription:
      "Mendampingi pelaku UMKM warung kecil dalam pengelolaan keuangan dan pemasaran digital.",
    description:
      "Banyak pelaku UMKM warung kecil di lingkungan padat penduduk belum memisahkan keuangan usaha dan pribadi, sehingga sulit berkembang. Komunitas Karsa mengadakan pendampingan berupa pelatihan pencatatan keuangan sederhana serta cara memasarkan produk melalui media sosial dan aplikasi pesan antar, dilengkapi konsultasi langsung dengan mentor bisnis dari relawan profesional.",
    date: "17 Januari 2026",
    time: "13.00 WIB",
    endTime: "16.00 WIB",
    location: "Balai RW 06, Kelurahan Pancoran Mas",
    address: "Jl. Pancoran Mas Raya, Depok",
    organizer: "Komunitas Karsa bersama mentor UMKM",
    participants: 33,
    maxParticipants: 40,
    target: "Mendampingi 30 pelaku UMKM warung kecil dalam pengelolaan keuangan dan pemasaran",
    impact: "33 pelaku UMKM mengikuti pendampingan dan 18 di antaranya berhasil membuka akun toko daring dalam sebulan",
    achievement: "Rata-rata omzet peserta program meningkat 15 persen dalam dua bulan",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Wahyu Ramadhan",
    contact: "0813-7745-2298",
    partner: "Asosiasi Mentor Bisnis Depok",
    volunteers: 9,
    budget: "Rp7.200.000",
    fundingSource: "Donasi mitra usaha dan warga",
    facilities: ["Modul pelatihan", "Konsumsi peserta", "Sesi konsultasi mentor"],
    requirements: ["Merupakan pelaku usaha aktif", "Membawa data usaha sederhana"],
    tags: ["Komunitas", "UMKM", "Pemberdayaan"],
    coverImage: COVER_KOMUNITAS,
    images: IMAGES_KOMUNITAS,
  },
  {
    id: "activity-018",
    title: "Gotong Royong Bersih Lingkungan Warga",
    slug: "gotong-royong-bersih-lingkungan-warga",
    category: "Komunitas",
    shortDescription:
      "Mengajak warga bergotong royong membersihkan saluran air dan area publik lingkungan.",
    description:
      "Menjelang musim hujan, saluran air di lingkungan RW 09 kerap tersumbat sampah sehingga menyebabkan genangan di beberapa titik jalan. Komunitas Karsa mengajak warga bergotong royong membersihkan saluran air, memangkas tanaman liar, dan menata ulang area publik seperti pos ronda dan taman kecil, sekaligus menjadi ajang mempererat kebersamaan antarwarga yang jarang bertemu karena kesibukan masing-masing.",
    date: "24 Februari 2026",
    time: "07.00 WIB",
    endTime: "10.00 WIB",
    location: "Lingkungan RW 09, Kelurahan Harjamukti",
    address: "Jl. Harjamukti Raya, Kota Bogor",
    organizer: "Komunitas Karsa bersama pengurus RW 09",
    participants: 75,
    maxParticipants: 90,
    target: "Membersihkan 1 km saluran air dan menata 3 titik fasilitas umum lingkungan",
    impact: "75 warga berpartisipasi, saluran air sepanjang 1,2 km berhasil dibersihkan dari sumbatan sampah",
    achievement: "Genangan air di 3 titik jalan utama berkurang signifikan sejak musim hujan berikutnya",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Agus Setiabudi",
    contact: "0857-6690-1123",
    partner: "Pengurus RW 09 Harjamukti",
    volunteers: 20,
    budget: "Rp5.600.000",
    fundingSource: "Swadaya warga",
    facilities: ["Alat kebersihan saluran", "Air minum", "Sarung tangan"],
    requirements: ["Menggunakan pakaian lapangan", "Membawa alat kebersihan pribadi (opsional)"],
    tags: ["Komunitas", "Gotong Royong", "Lingkungan"],
    coverImage: COVER_KOMUNITAS,
    images: IMAGES_KOMUNITAS,
  },
  {
    id: "activity-019",
    title: "Festival Karya Warga",
    slug: "festival-karya-warga",
    category: "Komunitas",
    shortDescription: "Menampilkan hasil kerajinan dan kuliner warga dalam festival komunitas tahunan.",
    description:
      "Festival Karya Warga digelar sebagai wadah bagi warga untuk menampilkan hasil kerajinan tangan, kuliner rumahan, hingga pertunjukan seni budaya lokal. Kegiatan ini bertujuan memperkuat rasa memiliki warga terhadap lingkungan tempat tinggal sekaligus membuka peluang usaha baru bagi pelaku ekonomi kreatif rumahan. Berbagai lomba seperti lomba masak dan lomba menghias sepeda hias turut memeriahkan suasana festival.",
    date: "15 Maret 2026",
    time: "08.00 WIB",
    endTime: "17.00 WIB",
    location: "Lapangan Kelurahan Sukatani",
    address: "Jl. Sukatani Raya, Kota Depok",
    organizer: "Komunitas Karsa bersama karang taruna dan PKK setempat",
    participants: 300,
    maxParticipants: 350,
    target: "Menghadirkan 40 lapak warga dan menjangkau minimal 250 pengunjung",
    impact: "45 lapak warga berpartisipasi dan festival dihadiri lebih dari 300 pengunjung dari berbagai wilayah",
    achievement: "Festival menjadi agenda tahunan tetap Kelurahan Sukatani",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Nia Kurnia",
    contact: "0812-8871-4456",
    partner: "Karang Taruna dan PKK Sukatani",
    volunteers: 40,
    budget: "Rp20.500.000",
    fundingSource: "Swadaya warga dan sponsor lokal",
    facilities: ["Sound system", "Tenda dan kursi", "Konsumsi peserta"],
    requirements: ["Mendaftar melalui panitia RW", "Membawa perlengkapan pribadi"],
    tags: ["Komunitas", "Festival", "Kuliner"],
    coverImage: COVER_KOMUNITAS,
    images: IMAGES_KOMUNITAS,
  },
  {
    id: "activity-020",
    title: "Pelatihan Kewirausahaan Pemuda",
    slug: "pelatihan-kewirausahaan-pemuda",
    category: "Komunitas",
    shortDescription: "Membekali pemuda dengan keterampilan merintis usaha mandiri sejak dini.",
    description:
      "Tingginya angka pemuda usia produktif yang belum memiliki pekerjaan tetap di wilayah pinggiran kota mendorong Komunitas Karsa menyelenggarakan pelatihan kewirausahaan dasar. Materi yang diberikan meliputi cara menemukan ide usaha, menyusun rencana bisnis sederhana, hingga strategi pemasaran melalui media sosial. Di akhir pelatihan, peserta diberi kesempatan mempresentasikan rencana usaha mereka di hadapan mentor bisnis lokal.",
    date: "26 April 2026",
    time: "09.00 WIB",
    endTime: "15.00 WIB",
    location: "Gedung Serbaguna Kecamatan Ciputat",
    address: "Jl. Ciputat Raya, Ciputat, Tangerang Selatan",
    organizer: "Komunitas Karsa bersama mentor bisnis muda",
    participants: 52,
    maxParticipants: 60,
    target: "Melatih 50 pemuda dalam menyusun rencana usaha mandiri",
    impact:
      "52 pemuda mengikuti pelatihan hingga tuntas dan 15 di antaranya berhasil merintis usaha rintisan dalam tiga bulan berikutnya",
    achievement: "Tiga peserta terbaik mendapat bantuan modal usaha awal dari mitra sponsor",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Fadli Ananta",
    contact: "0813-2245-6690",
    partner: "Komunitas Mentor Bisnis Muda",
    volunteers: 11,
    budget: "Rp11.800.000",
    fundingSource: "Sponsor lokal dan donasi warga",
    facilities: ["Modul kewirausahaan", "Konsumsi peserta", "Sesi presentasi mentor"],
    requirements: ["Usia 17-30 tahun", "Membawa ide usaha sederhana"],
    tags: ["Komunitas", "Kewirausahaan", "Pemuda"],
    coverImage: COVER_KOMUNITAS,
    images: IMAGES_KOMUNITAS,
  },
  {
    id: "activity-029",
    title: "Forum Komunitas Peduli Kampung",
    slug: "forum-komunitas-peduli-kampung",
    category: "Komunitas",
    shortDescription:
      "Menghadirkan forum diskusi warga untuk merumuskan program pembangunan kampung bersama.",
    description:
      "Forum Komunitas Peduli Kampung digagas sebagai ruang dialog terbuka antara warga, pengurus RT/RW, dan Komunitas Karsa untuk membahas permasalahan lingkungan, sosial, dan fasilitas umum di kampung. Diskusi menghasilkan beberapa usulan program prioritas yang kemudian ditindaklanjuti bersama, mulai dari perbaikan jalan lingkungan hingga penataan pos kamling.",
    date: "28 Juni 2026",
    time: "19.00 WIB",
    endTime: "21.00 WIB",
    location: "Balai Warga RW 10, Kelurahan Curug",
    address: "Jl. Curug Raya, Kecamatan Bojongsari, Depok",
    organizer: "Komunitas Karsa bersama pengurus RW 10",
    participants: 62,
    maxParticipants: 70,
    target: "Menghimpun aspirasi 50 warga terkait prioritas pembangunan kampung",
    impact: "62 warga hadir dan menghasilkan 5 program prioritas untuk ditindaklanjuti bersama",
    achievement: "Dua dari lima usulan program mulai direalisasikan dalam tiga bulan berikutnya",
    status: "Selesai",
    registration: "Pendaftaran ditutup",
    coordinator: "Ratna Dewi",
    contact: "0857-1123-4487",
    partner: "Pengurus RW 10 Curug",
    volunteers: 8,
    budget: "Rp2.900.000",
    fundingSource: "Swadaya warga",
    facilities: ["Sound system", "Kursi peserta", "Konsumsi ringan"],
    requirements: ["Merupakan warga setempat", "Mendaftar melalui pengurus RT/RW"],
    tags: ["Komunitas", "Forum Warga", "Musyawarah"],
    coverImage: COVER_KOMUNITAS,
    images: IMAGES_KOMUNITAS,
  },
  {
    id: "activity-030",
    title: "Kegiatan Olahraga Sehat Warga Ceria",
    slug: "kegiatan-olahraga-sehat-warga-ceria",
    category: "Komunitas",
    shortDescription:
      "Menggerakkan warga hidup aktif melalui senam bersama dan jalan sehat lingkungan.",
    description:
      "Untuk mendorong pola hidup sehat sekaligus mempererat kebersamaan warga, Komunitas Karsa menggelar kegiatan olahraga bersama berupa senam pagi dan jalan sehat mengelilingi lingkungan perumahan. Kegiatan ini diikuti warga dari berbagai usia dan ditutup dengan pembagian doorprize serta pemeriksaan kesehatan ringan bagi peserta lanjut usia.",
    date: "6 Desember 2026",
    time: "06.00 WIB",
    endTime: "09.00 WIB",
    location: "Lapangan Perumahan Bukit Cimanggu City",
    address: "Jl. Bukit Cimanggu City, Kota Bogor",
    organizer: "Komunitas Karsa bersama pengurus perumahan",
    participants: 180,
    maxParticipants: 200,
    target: "Melibatkan 150 warga dalam kegiatan senam dan jalan sehat bersama",
    impact: "180 warga berpartisipasi dan 25 peserta lansia mendapat pemeriksaan kesehatan gratis",
    achievement: "Kegiatan mendorong terbentuknya klub jalan sehat mingguan warga",
    status: "Akan Datang",
    registration: "Pendaftaran dibuka",
    coordinator: "Bayu Setiawan",
    contact: "0812-6690-3312",
    partner: "Pengurus Perumahan Bukit Cimanggu City",
    volunteers: 22,
    budget: "Rp9.700.000",
    fundingSource: "Swadaya warga dan sponsor produk kesehatan",
    facilities: ["Sound system", "Doorprize", "Alat cek kesehatan dasar"],
    requirements: ["Menggunakan pakaian olahraga", "Membawa air minum pribadi"],
    tags: ["Komunitas", "Olahraga", "Hidup Sehat"],
    coverImage: COVER_KOMUNITAS,
    images: IMAGES_KOMUNITAS,
  },
]